### ISSUE TITLE
Feasibility of using Prism parser

### ISSUE THREAD

**Issue by faraazahmad** [hasumikin/mruby-pico-compiler#20]
Now that there is a standalone parser (https://github.com/ruby/prism), I was wondering how feasible is it to use that for this repo? Prism is more feature complete and will become the only parser going forward for Ruby.

Having said that:
1. How much work could it take to replace the current implementation (tokenizer & parser) for picoruby?
2. Does it provide features picoruby doesn't need? Will that drastically effect the memory available in microcontrollers?

**Comment by hasumikin** [comment]
> Prism is more feature complete

"feature complete" means it likely uses more memory. It may become a barrier to adopting it for PicoRuby.

> and will become the only parser going forward for Ruby.

I don't think so. https://github.com/ruby/lrama by @yui-knk would be another option.

> How much work could it take to replace the current implementation (tokenizer & parser) for picoruby?

I don't know. I can't say anything unless I try it anyway.

> Does it provide features picoruby doesn't need? Will that drastically effect the memory available in microcontrollers?

That's the point. 
The least we can say is that the benefits of adopting YARP cannot be replaced by the critical disadvantage which is an unacceptable increase in RAM usage, the most important thing for PicoRuby.
So I am not willing to try YARP for now as I have a lot of backlogs to do.

**Comment by faraazahmad** [comment]
Understood! Your points totally make sense. I'd only raised this issue since TruffleRuby, JRuby, Natalie-Lang are switching to using Prism by default, so Ruby implementations can all depend on a single parser.

But if the RAM usage is an issue here, then I agree it becomes a non-starter. How can I measure the RAM usage for different parsers: Ripper, Prism, LRAMA, pico-compiler?

**Comment by hasumikin** [comment]
> How can I measure the RAM usage for different parsers: Ripper, Prism, LRAMA, pico-compiler?

It's a tough question :)
As I said at RubyConfTH, we can measure by `valgrind`.
See page 42 of https://slide.rabbit-shocker.org/authors/hasumikin/RubyConfTH2023/
However, measuring only the compiler's memory consumption would be difficult.
Difficult to align various conditions:
eg: As Ripper runs with CRuby implementation itself, valgrind's figure will contain CRuby's memory consumption.
eg: pico-compiler contains VM code generator while some of the others don't

We will first need to decide what conditions need to be met, and then some development work will be needed to set those conditions.
